### ISSUE TITLE
OCR number image

### ISSUE THREAD

**Issue by ericxin1982** [TobiasPSP/PsOcr#5]
Hi @TobiasPSP 

Does it be able to OCR digital image?
I tried, and it seems not able to see it, any option can be used to enable that?

Thanks
Eric Xin

**Comment by TobiasPSP** [comment]
The module takes any image file with supported type (i.e. jpg) and OCRs it. You may want to remove the parameter -Language so you don’t accidentally choose a ocr language that is not available. Prerequisite is that your Windows has at least one ocr language installed. You can control this in the control panel regional settings where you can add more languages (ocr, ui, text-to-speech, etc).

**Comment by ericxin1982** [comment]
How about those hand written character recognition? It looks like it cannot be recognized well.

**Comment by TobiasPSP** [comment]
The Windows OCR engine used here works for typed text only. Handwriting recognition is not supported by the particular OCR engine used in this code. Sorry for the misunderstanding.

**Comment by ericxin1982** [comment]
Thanks
